$schema: https://aka.ms/winget-packages.schema.2.0.json
packages:
  - packageIdentifier: Microsoft.VisualStudioCode 
  - packageIdentifier: Spotify.Spotify
  - packageIdentifier: 7zip.7zip                  # File Compression/Extraction
  - packageIdentifier: lars-berger.GlazeWM        # Tiling Window Manager
  - packageIdentifier: Microsoft.PowerToys        # Extra Windows Utilities
  - packageIdentifier: Microsoft.WindowsTerminal
  - packageIdentifier: WinDirStat.WinDirStat      # Drive Space Analyzer
  - packageIdentifier: AutoHotkey.AutoHotkey      # AutoHotkey
  - packageIdentifier: splode.pomotroid           # Pomodoro Timer